### ISSUE TITLE
Can't upload or generate feature graphic

### ISSUE THREAD

**Issue by lucasvanhalst** [our-city-app/plugin-mobicage-control-center#33]
```
Internal Server Error: /api/apps/be-aalst/images/generate Traceback (most recent call last): 
File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner response = get_response(request) 
File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response response = self.process_exception_by_middleware(e, request) 
File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response response = wrapped_callback(request, *callback_args, **callback_kwargs) 
File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view return view_func(*args, **kwargs) 
File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view return self.dispatch(request, *args, **kwargs) 
File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 483, in dispatch response = self.handle_exception(exc) 
File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 443, in handle_exception self.raise_uncaught_exception(exc) 
File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 480, in dispatch response = handler(request, *args, **kwargs) 
File "/usr/local/lib/python2.7/site-packages/rest_framework/decorators.py", line 52, in handler return func(*args, **kwargs) 
File "/code/app_configurator/bizz/authentication.py", line 137, in _arguments_wrapper return view_method(request, *args, **kwargs) 
File "/code/app_configurator/bizz/config.py", line 77, in _arguments_wrapper return view_method(request, *args, **kwargs) 
File "/code/app_configurator/restapi/appearance.py", line 111, in generate_image_types return JSONResponse(config.generate_images(image, image_types))
File "/code/app_configurator/bizz/config.py", line 300, in generate_images self.store_image_of_type(generated_image, image_type, background_color=None) 
File "/code/app_configurator/bizz/config.py", line 291, in store_image_of_type self.store_image(image, image_path) 
File "/code/app_configurator/bizz/config.py", line 273, in store_image image.save(path, subsampling=0, quality=100) 
File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 1935, in save save_handler(self, fp, filename) 
File "/usr/local/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 622, in _save raise 
IOError("cannot write mode %s as JPEG" % im.mode) IOError: cannot write mode RGBA as JPEG
```

**Comment by abom** [comment]
http://gitlab.mobicage.com/rogerthat/app-configurator/merge_requests/3
